name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: '42 * * * *'
  workflow_dispatch:

jobs:
  build-in-container:
    runs-on: ubuntu-latest
    container:
      image: python:3.14
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: szabgab/monitor@main
        with:
          config: sites/code-maven.com.yaml


