name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: '42 * * * *'
  workflow_dispatch:

jobs:
  build-in-container:
    runs-on: ubuntu-latest
    container:
      image: python:3.14
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # Pass the name of the individual config files
      - uses: szabgab/monitor@v1.00
        with:
          config: sites/code-maven.com.yaml sites/szabgab.com.yaml

      # Pass wild-card should also work
      - uses: szabgab/monitor@v1.00
        with:
          config: sites/*.yaml


      # Use the main branch
      - uses: szabgab/monitor@main
        with:
          config: sites/*.yaml


